// <auto-generated />
using Food2U.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Food2U.Migrations
{
    [DbContext(typeof(Food2UDbContext))]
    partial class Food2UDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Food2U.Models.DeliveryPerson", b =>
                {
                    b.Property<int>("deliverypersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vehichle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("deliverypersonID");

                    b.ToTable("DeliveryPerson");
                });

            modelBuilder.Entity("Food2U.Models.Items", b =>
                {
                    b.Property<int>("itemsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("itemsID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Food2U.Models.LocalRestaurants", b =>
                {
                    b.Property<int>("localrestaurantsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Menu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("localrestaurantsID");

                    b.ToTable("LocalRestaurants");
                });

            modelBuilder.Entity("Food2U.Models.Shoppers", b =>
                {
                    b.Property<int>("shoppersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("shoppersID");

                    b.ToTable("Shoppers");
                });
#pragma warning restore 612, 618
        }
    }
}
